version: '3'

services:

  master:
      image: mariadb
      restart: always
      command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
      environment:
        MYSQL_DATABASE: demo
        MYSQL_USER: demo
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
      volumes:
        - ./mariadb/mysql:/var/lib/mysql
        - ./mariadb/sql:/docker-entrypoint-initdb.d

  web:
      build: ./python
      image: django/web
      command: uwsgi --socket :8000 --module _config.wsgi --py-autoreload 1 --logto /tmp/mylog.log
      volumes:
        - ./applications:/applications
      expose:
        - "8000"
      environment:
        DATABASE_NAME: demo
        DATABASE_USER: demo
        DATABASE_PASSWORD: secret
      depends_on:
        - master

  nginx:
      build: ./nginx
      image: nginx/server
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./applications/django/static:/static
      environment:
        SERVER_NAME: example.com
        BACKEND_HOST: web:8000
        WORKER_PROCESSES: 1
        WORKER_CONNECTIONS: 1024
        KEEPALIVE_TIMEOUT: 65
        BACKEND_MAX_FAILS: 3
        BACKEND_MAX_TIMEOUT: 10s
        LOG_STDOUT: "true"
        ADMIN_EMAIL: demo@example.com
      depends_on:
        - web
